# -*- coding: utf-8 -*-
"""応用情報科学_report.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Yw85NPHC5GMsNdHlUzBYZ9dhIeCV_2Y
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np

#読み込む動画のある場所のパスを格納
path = "/content/drive/MyDrive/Colab Notebooks/dataset/videos/Detection.mp4"
video3 = cv2.VideoCapture(path)

ret, frame1 = video3.read()
frame1_g = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
change_amounts = []

while True:
  ret, frame2 = video3.read()
  if not ret:
    break

  frame2_g = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

  difference = np.abs(frame1_g.astype(np.int16) - frame2_g.astype(np.int16))

  change_amount = np.sum(difference)
  change_amounts.append(change_amount)

  frame1_g = frame2_g

video3.release()

plt.plot(change_amounts)
plt.xlabel('frame num')
plt.ylabel("change amounts")
plt.show()

#閾値の設定、今回の考察箇所
threshold = np.mean(change_amounts) * 10

change_frames = [i for i, v in enumerate(change_amounts) if v > threshold]
print('Change frames:', change_frames)